package com.frameium.pageobject.ODBM;

import com.frameium.genericfunctions.GenericFunctions;
import com.frameium.utilities.AutoGenerateData.AutoDataGeneration;
import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;

public class ODBMEmail extends GenericFunctions {
    WebDriver driver;
    GenericFunctions genericFunctions;
    WebDriverWait wait;

    public ODBMEmail(WebDriver driver){
        this.driver = driver;
        genericFunctions = new GenericFunctions(driver);
        this.wait = new WebDriverWait(driver, Duration.ofSeconds(50));
    }

    public String emailSubscription(String firstname, int firstNamelength, int lastlength, String mailType)throws Exception{
        Thread.sleep(2000);
        try{
            WebElement firstele = wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath(BreadWebElements.firstSubscribename)));
            WebElement lastele = wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath(BreadWebElements.lastSubscribename)));
            WebElement emailsubele = wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath(BreadWebElements.emailSubscribename)));
            String randomNames = AutoDataGeneration.randomGetname(firstname, firstNamelength);
            String randomlast = AutoDataGeneration.generateRandomlastName(lastlength);
            String randomemail = AutoDataGeneration.diffFormatEmail(mailType);
            firstele.sendKeys(randomNames);
            lastele.sendKeys(randomlast);
            emailsubele.sendKeys(randomemail);
            return randomNames + randomlast + randomemail;
        }
        catch (StaleElementReferenceException e){
            System.out.println("elements not found " + e.getMessage());
            return null;
        }

    }
    public void startEmailsubscribe(){
        WebElement emailele = wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath(BreadWebElements.Emailbtn)));    //encapsulating the webelement.
        clickElement(emailele);
    }


    public void suscribeAction()throws Exception{
        try{
            WebElement subscribele = wait.until(ExpectedConditions.elementToBeClickable(By.xpath(BreadWebElements.subscribeBtn)));
            clickElement(subscribele);
        }
        catch (TimeoutException e){
            System.out.println("elements not found ");
            e.fillInStackTrace();
        }
    }
    //for getting and returning the text, so we are using String as DataType.
    public String getSubscribermsg(){
        WebElement msgele = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(BreadWebElements.subscriberMsg)));
        return msgele.getText();
    }




}
