package com.frameium.utilities.AutoGenerateData;

import com.github.javafaker.Faker;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class AutoDataGeneration {
    public static String randomaddress;
    public static String randomnames;
    public static String randomzip;
    public static String randommail;
    public static String randomlast;
    public static String randomphone;
    public static String randomcity;
    public static String randomDate;
    private static final Faker fakes = new Faker();
    private static final Random randomee = new Random();



    public static void genrateRandomnames() {
        Faker faker = new Faker();
        String Names = faker.name().firstName();
        randomnames = Names;
    }
    public static List<String> nameformat(){
        Faker faker = new Faker();
        List<String> namelist = new ArrayList<>();      //creating list.
        String names =  faker.name().firstName();        //getting first name and store in names.
        namelist.add(names);                 //adding names to the list.
        return namelist;             //return the updated list.
    }

    public static String medicines(){
        Faker faker = new Faker();
        String medicines = faker.medical().medicineName();
        return medicines;
    }
    public static String randomGetname(String formatType, int firstNamelength) {
        String lastName = fakes.name().lastName();
        String firstName = generateFirstnamewithLength(firstNamelength);
        String fullName;
        if (formatType.equalsIgnoreCase("first last")) {
            fullName = firstName + " " + lastName;
        } else if (formatType.equalsIgnoreCase("Last, First")) {
            fullName = lastName + " ," + firstName;
        } else if (formatType.equalsIgnoreCase("F. last")) {
            fullName = firstName.charAt(0) + "." + lastName;                   //getting first character of the word
        } else if (formatType.equalsIgnoreCase("Full name")) {
            fullName = fakes.name().fullName();
        } else {
            fullName = firstName + " " + lastName;
        }
        return fullName;
    }
    public static String generateFirstnamewithLength(int length){
        String names = fakes.name().firstName();
        if(length == names.length()){
            return names;
        } else if (length <names.length()) {               //if generated name is greater than the given lenght
            return names.substring(0,length);
        }
        else {
            StringBuilder newName = new StringBuilder(names);
            while (newName.length()<length){
                char randomChar = (char) ('a' + randomee.nextInt(26));
                newName.append(randomChar);
            }
            return newName.toString();
        }
    }

    public static String generateRandomFakerlast() {
        Faker faker = new Faker();
        return randomlast = faker.address().lastName();
        //System.out.println(randomlast);
    }

    public static String generateRandomlastName(int length){
        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        StringBuilder lastName = new StringBuilder();
        Random random = new Random();

        for (int i = 0; i < length; i++) {
            lastName.append(characters.charAt(random.nextInt(characters.length())));
        }

        return lastName.toString();
    }
    public static String generateRandomMail() {
        Faker faker = new Faker();
        String username = faker.internet().emailAddress();
        String[] domain = {"example.com", "test.org", "asp.net", "demo.io", "test.ng"};
        String diffdomain = domain[new Random().nextInt(domain.length)];
        return randommail = username + "@" + diffdomain;
    }
    public static String diffFormatEmail(String mailType){
        Random random = new Random();
        Faker faker = new Faker();
        String names = faker.name().username();
        int numbers = random.nextInt(100);
        String email;
        //Handling different formats based on user input from cucumber
        if(mailType.equalsIgnoreCase("default")){
            email = names + numbers + "@gmail.com";
        } else if (mailType.equalsIgnoreCase("domainOrg")) {
            email = names + numbers + "@domain.org";
        } else if (mailType.equalsIgnoreCase("testingIo")) {
            email = names + numbers + "testing.io";
        } else if (mailType.equalsIgnoreCase("underscore")) {
            email = names + numbers + "@company.net";
        }
        else {
            email = mailType.replace("{random", String.valueOf(numbers)) + "@custom.com";
        }
        return email;
    }

    /// /Ri
    public static void generateRandomDate(String dateformat) {
        Faker faker = new Faker();
        String username = faker.internet().emailAddress();
        String[] domain = {"example.com", "test.org", "asp.net", "demo.io", "test.ng"};
        String diffdomain = domain[new Random().nextInt(domain.length)];
        randommail = username + "@" + diffdomain;

    }

    public static void generatePhone() {
        Random random = new Random();
        StringBuilder phonenum = new StringBuilder("91");
        int firstdigit = random.nextInt(6, 9);    //always number starts with between 6 & 9
        phonenum.append(firstdigit);
        //generating remaining digits
        for (int n = 0; n < 9; n++) {
            int digit = random.nextInt(0, 9);
            phonenum.append(digit);
        }
        randomphone = phonenum.toString();
    }

    public static void generateRandomZip() {
        Random random = new Random();
        int digits = random.nextInt(1000, 9999);    //generating random 4 digit numbers from 1000 to 9999
        randomzip = String.valueOf(digits);      //store the result as a string in the globalvariable.
    }

    public static void getRandomaddress() {
        Faker faker = new Faker();
        randomaddress = faker.address().fullAddress();
        //return faker.address().fullAddress();
    }

    public static void generateRandomcity() {
        Faker faker = new Faker();
        String cities = faker.address().city();
        randomcity = cities;
    }

    public static void DateReg() {
        Random random = new Random();
        int year = random.nextInt(2025) + 1950;
        int date = random.nextInt(31) + 1;      //generating days from 1 to 31
        int month = random.nextInt(12) + 1;
        String formatedDate = date + "/" + month + "/" + year;
        randomDate = formatedDate;
    }

    public static String FormateDate(String format) {
        Random random = new Random();
        int randomdays = random.nextInt(365);
        LocalDate randomdate = LocalDate.now().minusDays(randomdays);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern(format);
        return randomdate.format(formatter);
    }

    //By using If-else condition for cucumber framework.
    public static String FormatDate3(String formatType){
        Random random = new Random();
        int randomDays = random.nextInt(365); // Generate a random number of days
        LocalDate randomDate = LocalDate.now().minusDays(randomDays);          //getting current date.
        DateTimeFormatter formatter;

        // If-Else condition to select different date formats
        if (formatType.equalsIgnoreCase("MM/dd/yyyy")) {
            formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
        } else if (formatType.equalsIgnoreCase("dd-MM-yyyy")) {
            formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        } else if (formatType.equalsIgnoreCase("yyyy/MM/dd")) {
            formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        } else if (formatType.equalsIgnoreCase("EEE, MMM d, yyyy")) {
            formatter = DateTimeFormatter.ofPattern("EEE, MMM d, yyyy");
        } else {
            // Default format if no valid input is provided
            formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
        }

        return randomDate.format(formatter);
    }


}
